### ISSUE TITLE
Python version needs updating.

### ISSUE THREAD

**Issue by sstene1** [Senzing/docker-senzing-debug#10]
Senzing debug docker container still references Python 2.7.13 instead of the required Python 3.6.

**Comment by docktermj** [comment]
@sstene1 Can you be specific on where you see the use of 2.7.13?

On DockerHub  (https://hub.docker.com/r/senzing/senzing-debug/tags)  we updated to the use of Python3  (3.7) about a week ago.  Either of these should get the latest version:

```console
sudo docker pull senzing/senzing-debug
```
or
```console
sudo docker pull senzing/senzing-debug:1.1.0
```

A search of the repository (https://github.com/Senzing/docker-senzing-debug/search?q=2.7&unscoped_q=2.7) doesn't reveal anything referencing 2.7.13.

Let me know where you see 2.7.13,  I'd be happy to update it.

**Comment by sstene1** [comment]
I pull the latest tag. I’ll pull down the 1.1.0 image.

**Comment by docktermj** [comment]
@sstene1,  Here's the current state of the container:

```console
$ docker run -it senzing/senzing-debug:1.2.2 /bin/bash
```

In docker container:

```console
# python --version
Python 2.7.13

# python3 --version
Python 3.7.3
```

Is that sufficient?

**Comment by docktermj** [comment]
@sstene1 Have we satisfied your concern? If not, please let us know. 

If we don't hear back in a week, we'll close the issue for you.

**Comment by docktermj** [comment]
Having not heard back in a week,  I'm closing this issue.  If it still an issue please request that it be re-opened or submit a new issue.
